runtime: python27
api_version: 1
threadsafe: true

automatic_scaling:
  max_instances: 1

handlers:
- url: /assets
  static_dir: assets

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: poker.application

- url: /.*
  script: poker.application
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
